version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-node-browsers
    working_directory: ~/spring-music
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
      - run:
          name: Building the application
          command: ./gradlew clean assemble
      - save_cache:
          key: gradle-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle/caches
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    docker:
      - image: govau/cf-cli
    working_directory: ~/spring-music
    steps:
      - attach_workspace:
          at: ~/spring-music
      - run:
          name: Deploying to cloud.gov.au
          command: ./scripts/deploy.sh
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - develop
