version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-node-browsers
    working_directory: /app
    steps:
      - checkout
      - run:
          name: Building the application
          command: ./gradlew clean assemble
      - persist_to_workspace:
          root: /app
          paths:
            - .
  deploy:
    docker:
      - image: govau/cf-cli
    working_directory: /app
    steps:
      - attach_workspace:
          at: /app
      - run:
          name: Deploying to cloud.gov.au
          command: ./scripts/deploy.sh
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - develop
